# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaedfe8bc339b8c2ddcd3451fa8ed754671918274c9cd1822259f90e08521c0f7c910765cf3a16c3c87c15b7199fb6f9f8a7d017708d376c0f6c3729a869e0b3

test:
  secret_key_base: 4907d1154df851ed40253a224c669cd93eb6ccb0c1d9d3647789d40865eb63b4ed6117efadd9d257f05ba2e65a44d225ae35f48be33f00e288ab675508257fae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
